### PR TITLE
Fixed id generation for first time setup

### LINKED ISSUE #41: Add a way of generating the inital identities for the config file
**Describe the bug**
Currently it is impossible to start the bot without having at least the master and one music bot identity.

**To Reproduce**
1. Clone the repository
2. Try to generate identities with '-g'

**Expected behavior**
The bot should generate a master identity and a music bot identity if they are missing.

### PR DESCRIPTION
**Pull request by Jokler**
**Summary**
This PR fixes the following **bugs**

* Identity generation does not work during first time setup

**Closing issues**
Resolves #41.

### CODE REVIEW

File: src/main.rs [hunk 1]
```diff
@@ -94,6 +103,15 @@ fn run() -> Result<(), Box<dyn std::error::Error>> {
...
     }
 
+    if config.id.is_none() {
+        error!("Failed to find identity for the master bot, try running with `-g`");
+        return Ok(());
+    }
+    if config.ids.is_none() {
+        error!("Failed to find identies for the music bots, try running with `-g`");
+        return Ok(());
+    }
```
Comment (fkaa) [inline src/main.rs]: merge conditions

**Review by fkaa — CHANGES_REQUESTED** [review]

**Review by fkaa — APPROVED** [review]
