### PR TITLE
Fix panic if a user can not be found and subscribe to new channels

### LINKED ISSUE #26: The bot panics if a user pokes it from a channel the bot is not subscribed to
**Describe the bug**
The user pokes the bot which causes it to panic and as a result the master bot disconnects.

**To Reproduce**
I have been able to reproduce this by creating a new channel and switching to it.

**Expected behavior**
The bot should be able to join the channel even after it just got created. In general this panic should be removed to prevent these kind of bugs from crashing the master bot in the future.

**Additional context**
Relevant LOC:
https://github.com/Mavulp/pokebot/blob/3575ac579cdcc5a9fa3ffec84952a634d1d7deaf/src/bot/master.rs#L107

### PR DESCRIPTION
**Pull request by Jokler**
**Summary**
This PR fixes the following **bugs**

- [x] The bot does not automatically subscribe to channels that are created
- [x] It panics if it can't find the user

**Closing issues**
Resolves #26.

### CODE REVIEW

File: src/bot/master.rs [hunk 1]
```diff
@@ -192,22 +173,32 @@ impl MasterBot {
...
+        match message {
+            MusicBotMessage::TextMessage(message) => {
+                if let MessageTarget::Poke(who) = message.target {
+                    info!("Poked by {}, creating bot for their channel", who);
+                    self.spawn_bot_for(who).await;
+                }
+            }
+            MusicBotMessage::ChannelCreated(_) => {
+                // TODO Only subscribe to one channel
+                self.teamspeak.subscribe_all();
```
Comment (Jokler) [inline src/bot/master.rs:199]: This is a bit ugly but to subscribe to only one channel a new method has to be added to `tsclientlib` first.
